// JSON test data for images, will be read during function openImageBox //

var images = [
	{'name' : '01__cat',
	'category' : 'Cat Image',
    'source' : '.jpg',
    'sourcMedium' : '-800.jpg',
	'sourceSmall' : '-400.jpg',
	'preview' : '-preview.jpg',
	'date' : 20161207,
	'title' : 'Cat One',
	'description' : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut cursus ullamcorper dui. Nam tristique cursus malesuada. Suspendisse est sem, sollicitudin vitae fermentum eget, suscipit id lacus. Aliquam pharetra sagittis lorem et lobortis. Sed gravida egestas mauris ac mollis. Aliquam mattis diam et gravida ultrices. Ut sagittis, libero ac elementum fermentum, magna erat dictum urna, sed feugiat risus lectus id lectus. Curabitur eget ipsum vitae eros posuere cursus. Sed eget mattis risus. Aliquam venenatis nisi non tincidunt commodo. Cras tellus lorem, varius at vestibulum ut, rutrum non sapien. Ut quis ipsum a libero pharetra aliquam id nec nulla.<br>Integer a accumsan eros. In mattis posuere dui commodo varius. Curabitur semper vitae sapien in convallis. Aenean ultricies tincidunt leo, sed sollicitudin lacus porttitor pretium. Duis tristique lectus sed nisi interdum aliquet. Phasellus ut nibh nisl. Fusce quis lobortis turpis. Curabitur dapibus sapien eget mauris luctus euismod. Phasellus sodales nunc orci. Aliquam erat volutpat.'},
	{'name' : '02__cat',
	'category' : 'Cat Image',
	'source' : '.jpg',
    'sourcMedium' :  '-800.jpg',
	'sourceSmall' :  '-400.jpg',
	'preview' : '-preview.jpg',
	'date' : 20161206,
	'title' : 'Cat Two',
	'description' : 'Nunc rhoncus pretium diam, quis pellentesque sem dictum quis. Aenean et nulla eu eros fermentum vehicula non sit amet libero. Quisque sollicitudin interdum maximus. Quisque dignissim mattis libero et placerat. Quisque venenatis massa a finibus luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus quis sapien et odio dictum sollicitudin sit amet eu augue. Morbi cursus, elit sed vehicula finibus, nunc ipsum vehicula nisi, vel scelerisque ex est sed velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin efficitur, mauris nec aliquam porttitor, odio eros feugiat nulla, in pulvinar ligula ex id metus. Vestibulum consequat sagittis ultricies. Sed leo enim, fringilla eget hendrerit eu, facilisis non diam. Sed quis faucibus nunc, in aliquet mi. Nulla placerat massa nisl, sed suscipit tortor mattis ut. Morbi condimentum eu arcu in euismod. Sed sed tristique lorem.'},
	{'name' : '03__cat',
	'category' : 'Cat Image',
	'source' : '.jpg',
    'sourcMedium' : '-800.jpg',
	'sourceSmall' : '-400.jpg',
	'preview' : '-preview.jpg',
	'date' : 20161205,
	'title': '<h1>Cat Three</h1>' ,
	'description' : 'Duis sit amet neque ut risus ultrices tempor at eget augue. Suspendisse sodales nisl at urna finibus, in vestibulum magna vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam aliquam arcu vitae metus cursus, vel pulvinar elit eleifend. Mauris arcu leo, mattis tempor feugiat eu, finibus non elit. Fusce vitae ultricies massa, sed rutrum sem. Maecenas nec turpis in erat tincidunt faucibus. Fusce ornare tincidunt nisl aliquam rutrum. Suspendisse id dolor tincidunt, luctus nisi a, hendrerit dolor. Curabitur a ante quis nibh ornare feugiat ut ut enim. Pellentesque pulvinar orci nec tortor dictum, non placerat metus accumsan. Mauris aliquet enim id mauris volutpat porttitor. Phasellus mattis laoreet nunc a auctor. Donec pellentesque vehicula velit vel tempus. Nulla facilisi.Nulla felis risus, laoreet a nibh quis, interdum consequat nisl. Aliquam sollicitudin dapibus aliquam. Vestibulum id nunc a dui egestas eleifend eu eget turpis. Etiam lobortis, augue nec commodo aliquet, enim arcu egestas odio, vel vulputate augue eros vitae quam. Nam eu porta magna. Curabitur luctus, nisl ac laoreet porttitor, nibh massa accumsan dolor, nec finibus urna est a metus. Pellentesque aliquet gravida sem, in pretium orci convallis non. Integer tellus tortor, posuere in aliquet vestibulum, efficitur aliquam elit. Sed vehicula, sapien a eleifend ornare, quam metus facilisis risus, vitae facilisis nunc dui sit amet leo. Donec non nisi vitae nisi accumsan lobortis sit amet interdum odio. Donec orci massa, rhoncus ultrices congue sed, ultricies vel velit.'}]